name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test deps
        run: python -m pip install -U pytest
      - name: Run tests
        run: make test
      - name: Build lambda zip
        run: make package
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Terraform fmt/validate
        working-directory: infra
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate
